tools:
  - class_name: "verl.tools.drc_tools.MovePolygonTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "op_move_polygon"
        description: "通过给定的增量 (dx, dy) 移动布局中的指定“多边形”（实例）。"
        strict: True
        parameters:
          type: "object"
          properties:
            polygon_name:
              type: "string"
              description: "要移动的‘多边形’（实例）的名称。"
            dx:
              type: "number"
              description: "x 方向的移动距离 (um)。"
            dy:
              type: "number"
              description: "y 方向的移动距离 (um)。"
          required: ["polygon_name", "dx", "dy"]

  - class_name: "verl.tools.drc_tools.SplitPolygonTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "op_split_polygon"
        description: "使用一个无限长直线(x=value 或 y=value) 来分割一个多边形"
        strict: True
        parameters:
          type: "object"
          properties:
            polygon_name:
              type: "string"
              description: "要分割的‘多边形’（实例）的名称。"
              axis:
                type: "string"
                enum: ["x", "y"]
                description: "决定分割直线是 x=value 还是 y=value"
              value:
                type: "number"
                description: "直线的具体数值"
          required: ["polygon_name", "axis","value"]